### ISSUE TITLE
Can no longer access the site

### ISSUE THREAD

**Issue by soxfox42** [MaxBittker/broider#23]
Going to https://maxbittker.github.io/broider/ now redirects to [Never Gonna Give You Up](https://www.youtube.com/watch?v=dQw4w9WgXcQ). Strangely enough, this occurs even on a local clone, though I can't find any code that should trigger a redirect. I believe the site worked fine yesterday.

**Comment by MaxBittker** [comment]
fixing, someone xss

**Comment by MaxBittker** [comment]
thanks for the heads up
